name: Production deployment

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Hugo build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.94.0"
        extended: true

    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: public

  deploy:
    name: deploy ftp
    runs-on: ubuntu-latest
    needs: build
    steps:

    - uses: actions/download-artifact@v2.0.5
      with:
        name: build
        path: public

    - uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "public"